# Generated by Django 4.2.4 on 2023-10-02 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0015_rename_game_gamemedia_game_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='C:\\Users\\MikeyMike\\Desktop\\Courses\\AprilPy\\steamlite2\\staticimages/avatars/default.jpeg', upload_to='profiles/avatars/')),
                ('profile_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('background_img', models.CharField(choices=[(1, 'images/backgrounds/default.webp')], default=1, max_length=256)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField()),
                ('profile_level', models.IntegerField(default=0)),
                ('xp_level', models.IntegerField(default=0)),
                ('summary', models.CharField(max_length=256)),
                ('friend_list', models.ManyToManyField(to='profiles.profile')),
                ('game_list', models.ManyToManyField(to='games.gamemaininfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
