# Generated by Django 4.2.4 on 2023-10-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_rename_game_gamemedia_game_info'),
        ('profiles', '0002_profile_cart_profile_wishlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background_img',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='Cart', to='games.gamemaininfo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friend_list',
            field=models.ManyToManyField(blank=True, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='game_list',
            field=models.ManyToManyField(blank=True, related_name='GameList', to='games.gamemaininfo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='Wishlist', to='games.gamemaininfo'),
        ),
    ]
