# Generated by Django 4.2.4 on 2023-09-13 12:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('bit', models.IntegerField(choices=[(1, 32), (2, 64)], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[(1, 'Intel'), (2, 'AMD')], max_length=128)),
                ('core_type', models.CharField(blank=True, choices=[(1, 'Core'), (2, 'Dual-Core'), (3, 'Quad_core')], max_length=128, null=True)),
                ('name', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=50)),
                ('speed', models.DecimalField(decimal_places=1, help_text='GHz', max_digits=2, validators=[django.core.validators.MinValueValidator(1, 'Введенное значение ниже допустимого')])),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedRequiremrnts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specs.os')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specs.processor')),
            ],
        ),
        migrations.CreateModel(
            name='MinimumRequiremrnts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specs.os')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specs.processor')),
            ],
        ),
    ]
