# Generated by Django 4.2.4 on 2023-09-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='brand',
            field=models.CharField(choices=[('1', 'Intel'), ('2', 'AMD')], max_length=128),
        ),
        migrations.AlterField(
            model_name='processor',
            name='core_type',
            field=models.CharField(blank=True, choices=[('1', 'Core'), ('2', 'Dual-Core'), ('3', 'Quad_core')], max_length=128, null=True),
        ),
    ]
