# Generated by Django 4.2.4 on 2023-09-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_alter_processor_brand_alter_processor_core_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='brand',
            field=models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=128),
        ),
        migrations.AlterField(
            model_name='processor',
            name='core_type',
            field=models.CharField(blank=True, choices=[('Core', 'Core'), ('Dual', 'Dual-Core'), ('Quad_core', 'Quad_core')], max_length=128, null=True),
        ),
    ]
