# Generated by Django 4.2.4 on 2023-09-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0003_alter_processor_brand_alter_processor_core_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='bit',
            field=models.IntegerField(choices=[(32, 32), (64, 64)], default=2),
        ),
    ]
