# Generated by Django 4.2.4 on 2023-09-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_game_creator_game_publisher'),
        ('specs', '0004_alter_os_bit'),
    ]

    operations = [
        migrations.AddField(
            model_name='minimumrequiremrnts',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendedrequiremrnts',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
            preserve_default=False,
        ),
    ]
