# Generated by Django 4.2.4 on 2023-09-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_game_creator_game_publisher'),
        ('specs', '0005_minimumrequiremrnts_game_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MinimumRequiremrnts',
            new_name='MinimumRequirements',
        ),
        migrations.RenameModel(
            old_name='RecommendedRequiremrnts',
            new_name='RecommendedRequirements',
        ),
    ]
