# Generated by Django 4.2.4 on 2023-09-25 14:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specs', '0006_rename_minimumrequiremrnts_minimumrequirements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('NVIDIA', 'NVIDIA'), ('AMD', 'AMD')], default=None, max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('vram', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Не возможно ввести чило меньше 1')])),
            ],
        ),
        migrations.AddField(
            model_name='minimumrequirements',
            name='directX',
            field=models.CharField(choices=[('DirectX 9', 'DirectX 9'), ('DirectX 10', 'DirectX 10'), ('DirectX 11', 'DirectX 11'), ('DirectX 12', 'DirectX 12')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='minimumrequirements',
            name='ram',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='minimumrequirements',
            name='storage',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, 'Не возможно ввести чило меньше 1')]),
        ),
        migrations.AddField(
            model_name='recommendedrequirements',
            name='directX',
            field=models.CharField(choices=[('DirectX 9', 'DirectX 9'), ('DirectX 10', 'DirectX 10'), ('DirectX 11', 'DirectX 11'), ('DirectX 12', 'DirectX 12')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recommendedrequirements',
            name='ram',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recommendedrequirements',
            name='storage',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, 'Не возможно ввести чило меньше 1')]),
        ),
        migrations.CreateModel(
            name='UsersSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField(null=True)),
                ('graphics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='specs.graphics')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specs.os')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specs.processor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='minimumrequirements',
            name='graphics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='specs.graphics'),
        ),
        migrations.AddField(
            model_name='recommendedrequirements',
            name='graphics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='specs.graphics'),
        ),
    ]
