# Generated by Django 4.2.4 on 2023-08-23 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('early_access', models.DateField(verbose_name='Ранний доступ')),
                ('publish_date', models.DateField(verbose_name='Дата релиза')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Введено значение ниже допустимого')], verbose_name='Цена')),
                ('size', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Размер игры')),
                ('min_sys_req', models.TextField(verbose_name='Мин. системные требования')),
                ('rec_sys_req', models.TextField(verbose_name='Реком. системные требования')),
                ('is_singleplayer', models.BooleanField(default=False, verbose_name='Одиночная игра')),
                ('is_multiplayer', models.BooleanField(default=False, verbose_name='Мультиплэер')),
                ('has_crossplatforer', models.BooleanField(default=False, verbose_name='Кросплатформенная')),
                ('has_discount', models.BooleanField(default=False, verbose_name='Есть скидка')),
                ('discount_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка')),
                ('age_rist', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Возраст. органичение')),
            ],
        ),
    ]
