# Generated by Django 4.2.4 on 2023-08-28 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_icon',
            field=models.ImageField(null=True, upload_to='game_icons'),
        ),
        migrations.AddField(
            model_name='game',
            name='poster',
            field=models.ImageField(null=True, upload_to='game_posters'),
        ),
        migrations.CreateModel(
            name='GameMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='game_media')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
