# Generated by Django 4.2.4 on 2023-08-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_game_icon_game_poster_gamemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='early_access',
            field=models.DateField(blank=True, null=True, verbose_name='Ранний доступ'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_icon',
            field=models.ImageField(upload_to='game_icons'),
        ),
        migrations.AlterField(
            model_name='game',
            name='poster',
            field=models.ImageField(upload_to='game_posters'),
        ),
    ]
