# Generated by Django 4.2.4 on 2023-09-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_genre_alter_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='games.genre'),
        ),
    ]
