# Generated by Django 4.2.4 on 2023-09-11 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_dlc',
            field=models.BooleanField(default=False, verbose_name='Дополнительный контент'),
        ),
        migrations.AddField(
            model_name='game',
            name='main_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='games.game'),
        ),
    ]
