# Generated by Django 4.2.4 on 2023-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_is_dlc_game_main_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='poster',
            field=models.ImageField(null=True, upload_to='genre/'),
        ),
    ]
