# Generated by Django 4.2.4 on 2023-09-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_genre_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='poster',
            field=models.ImageField(default='C:\\Users\\MikeyMike\\Desktop\\Courses\\AprilPy\\steamlite/static/genre/default.jpg', null=True, upload_to='genre/'),
        ),
    ]
