# Generated by Django 4.2.4 on 2023-09-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_gamemaininfo_price_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemaininfo',
            name='price_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='games.gamepriceinfo'),
        ),
    ]
