# Generated by Django 4.2.4 on 2023-09-18 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_gamemaininfo_price_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesecondaryinfo',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
    ]
