# Generated by Django 4.2.4 on 2023-09-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_gamesecondaryinfo_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamemedia',
            old_name='game',
            new_name='game_info',
        ),
    ]
